import numpy as np 
english_score = np.array([55,89,76,65,48,70])
math_score = np.array([60,85,60,68,np.nan,60])
chinese_score = np.array([65,90,82,72,66,77])
#1.請計算各科成績平均、最大值、最小值、標準差，其中數學缺一筆資料可忽略？
mean_math = np.nanmean(math_score)
mean_english = np.mean(english_score)
mean_chinese = np.mean(chinese_score)
max_math = np.nanmax(math_score)
max_english = np.max(english_score)
max_chinese = np.max(chinese_score)
min_math = np.nanmin(math_score)
min_english = np.min(english_score)
min_chinese = np.min(chinese_score)
std_math = np.nanstd(math_score)
std_english = np.std(english_score)
std_chinese = np.std(chinese_score)
print(std_math)
print(std_english)
print(std_chinese)
print(max_math)
print(max_english)
print(max_chinese)
print(min_math)
print(min_english)
print(min_chinese)
print(mean_math)
print(mean_english)
print(mean_chinese)
#2.第五位同學補考數學後成績為 55，請計算補考後數學成績平均、最大值、最小值、標準差？
math_score[4] = 55
mean_math = np.nanmean(math_score)
mean_english = np.mean(english_score)
mean_chinese = np.mean(chinese_score)
max_math = np.nanmax(math_score)
max_english = np.max(english_score)
max_chinese = np.max(chinese_score)
min_math = np.nanmin(math_score)
min_english = np.min(english_score)
min_chinese = np.min(chinese_score)
std_math = np.nanstd(math_score)
std_english = np.std(english_score)
std_chinese = np.std(chinese_score)
print(std_math)
print(std_english)
print(std_chinese)
print(max_math)
print(max_english)
print(max_chinese)
print(min_math)
print(min_english)
print(min_chinese)
print(mean_math)
print(mean_english)
print(mean_chinese)
#3.用補考後資料找出與國文成績相關係數最高的學科？
#英文
print(np.corrcoef(chinese_score,math_score))
print(np.corrcoef(chinese_score,english_score))
print(np.correlate(chinese_score,math_score))
print(np.correlate(chinese_score,english_score))